project_name: accuknox

## go mod configurations
gomod:
    proxy: true
    env:
      - GOPRIVATE="github.com/accuknox/*"
    mod: mod

builds:
  - binary: accuknox
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
