project_name: accuknox

gomod:
    proxy: true
    env:
      - GOPRIVATE="github.com/accuknox/*"
    mod: mod
    gobinary: go1.18

builds:
  - binary: accuknox
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
